security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        doctrine:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: doctrine
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: "login[_username]"
                password_parameter: "login[_password]"
                always_use_default_target_path:  true
                default_target_path:  /
            logout: ~

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/users, roles: ROLE_ADMIN }

        - { path: ^/, roles: ROLE_USER }